#!/usr/bin/env python

from pyar_bh.bh import run_bh


def main():
    import argparse
    program_description = """A program to do global optimization with
    Differential Evolution algorithm using SciPy.optimize.differential_evolution
    Currently interfaced with ORCA and Gaussian packages.
    """
    example = """
    Example:
        python pyar-de.py start.xyz --software orca -c 0 -m 1 --keywords '! hf-3c'
    where start.xyz is input coordinate file in xyz format

    """
    parser = argparse.ArgumentParser(prog='pyar-bh',
                                     description=program_description,
                                     epilog=example,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)

    parser.add_argument("input_file", metavar='file.xyz',
                        type=str,
                        help='input file in xyz format')
    parser.add_argument("--software", type=str,
                        choices=['gaussian', 'orca'],
                        required=True, help="Software")
    # noinspection SpellCheckingInspection
    parser.add_argument('-nprocs', '--nprocs', metavar='n',
                        type=int, help='The number of processors/cores to be '
                                       'used by the quantum chemistry software.'
                        )
    parser.add_argument("-c", "--charge", type=int, required=True,
                        metavar='c',
                        help="Total charge of the system")
    parser.add_argument("-m", "--multiplicity", type=int,
                        required=True,
                        metavar='m',
                        help="Multiplicity of the system")
    parser.add_argument('--keywords', type=str, required=True,
                        help='Keyword line for the QM software input. '
                             'E.g., For gaussian input, "# PBE def2SVP"'
                             'Fro ORCA input, "! RI PBE def2-SVP D3BJ"')

    parser.add_argument('--extra-keywords', type=str,
                        help='Keyword line for the QM software input. '
                             'E.g., For gaussian input, "%%mem=2Gnk"'
                             'Fro ORCA input, and "%%scf maxiter=100 end"')

    args = parser.parse_args()
    run_bh(vars(args))


main()
